M48
; DRILL file {KiCad 8.0.1} date 2024-04-01T22:33:05+0800
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-04-01T22:33:05+08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.4104Y-2.7215
X4.4104Y-2.8317
T2
X5.7333Y-4.2087
M30
